- name: setup vps
  hosts: vps
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install lxc
      apt:
        name: lxc

    - name: install pip2
      apt:
        name: python-pip