- name: setup vps
  hosts: vps
  become: true
  become_user: root
  become_method: sudo
  tasks:
    # Needs lxc-dev for lxc-python2
    # https://github.com/ansible/ansible-modules-extras/issues/550
    - name: install lxc-dev
      apt:
        name: lxc-dev

    - name: install pip2
      apt:
        name: python-pip

    - name: install lxc-python2
      pip:
        name: lxc-python2

    - name: install bridge-utils
      apt:
        name: bridge-utils

    - name: check if bridge already exists
      shell: HAS_BRIDGE=$(ip a | grep br0); if [ ! -z "$HAS_BRIDGE" ]; then echo "yes"; else echo "no"; fi
      register: has_bridge

    - name: create the bridge
      shell: brctl addbr br0
      when: has_bridge.stdout.find("no") != -1

    - name: destroy jupyter container
      lxc_container:
        name: jupyter
        state: absent
      tags:
        - jupyter
    
    - name: start jupyter container
      lxc_container:
        name: jupyter
        template: debian
        state: started
      tags:
        - jupyter