- name: setup vps
  hosts: vps
  become: true
  become_user: root
  become_method: sudo
  tasks:
    # Needs lxc-dev for lxc-python2
    # https://github.com/ansible/ansible-modules-extras/issues/550
    - name: install lxc-dev
      apt:
        name: lxc-dev

    - name: install pip2
      apt:
        name: python-pip